<?php
declare(strict_types=1);

namespace Chanshige\Foundation;

use Chanshige\Foundation\Collection\ArrayList;

/**
 * Class CcTLDList
 *
 * @package Chanshige\Foundation\Collection
 */
final class CcTLDList extends ArrayList
{
    protected static $data = [
        'jp',
        'co.jp',
        'or.jp',
        'ne.jp',
        'ac.jp',
        'ed.jp',
        'go.jp',
        'ad.jp',
        'hokkaido.jp',
        'miyagi.jp',
        'fukushima.jp',
        'aomori.jp',
        'iwate.jp',
        'yamagata.jp',
        'akita.jp',
        'tokyo.jp',
        'kanagawa.jp',
        'saitama.jp',
        'chiba.jp',
        'ibaraki.jp',
        'gunma.jp',
        'tochigi.jp',
        'niigata.jp',
        'nagano.jp',
        'yamanashi.jp',
        'aichi.jp',
        'shizuoka.jp',
        'gifu.jp',
        'ishikawa.jp',
        'toyama.jp',
        'fukui.jp',
        'osaka.jp',
        'hyogo.jp',
        'kyoto.jp',
        'nara.jp',
        'mie.jp',
        'shiga.jp',
        'wakayama.jp',
        'hiroshima.jp',
        'okayama.jp',
        'yamaguchi.jp',
        'shimane.jp',
        'tottori.jp',
        'ehime.jp',
        'kagawa.jp',
        'tokushima.jp',
        'kochi.jp',
        'fukuoka.jp',
        'kumamoto.jp',
        'kagoshima.jp',
        'nagasaki.jp',
        'oita.jp',
        'miyazaki.jp',
        'saga.jp',
        'okinawa.jp',
        'ac',
        'am',
        'be',
        'bz',
        'cm',
        'cn',
        'cz',
        'gs',
        'mu',
        'mx',
        'co.uk',
        'me.uk',
        'org.uk',
        'vg',
        'vn',
        'id',
        'tw',
        'fr',
    ];
}
