<?php
/*
 * This file is part of the Chanshige\Whois package.
 *
 * (c) shigeki tanaka <dev@shigeki.tokyo>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

namespace Chanshige;

use PHPUnit\Framework\TestCase;

class CommonTestCase extends TestCase
{
    protected mixed $expected;
    protected mixed $actual;

    protected function setUp(): void
    {
        parent::setUp();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function verify($msg = null)
    {
        $this->assertEquals($this->expected, $this->actual, $msg);
    }
}
