<?php
namespace Chanshige;

use Chanshige\Handler\SocketInterface;
use PHPUnit\Framework\TestCase;

class CommonTestCase extends TestCase
{
    protected $expected;
    protected $actual;

    protected function setUp(): void
    {
        parent::setUp();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function verify(?string $msg = null): void
    {
        $this->assertEquals($this->expected, $this->actual, $msg ?? '');
    }

    protected function newWhois(SocketInterface $socket): Whois
    {
        $responseFactory = new ResponseFactory();
        $client = new WhoisClient($socket, $responseFactory);

        return new Whois(
            $client,
            new ServerResolver($client),
            new DomainNormalizer(),
            new WhoisRequestFormatter(),
            $responseFactory
        );
    }
}
