<?php
namespace Chanshige;

use PHPUnit\Framework\TestCase;

class CommonTestCase extends TestCase
{
    protected $expected;
    protected $actual;

    protected function setUp(): void
    {
        parent::setUp();
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function verify($msg = null)
    {
        $this->assertEquals($this->expected, $this->actual, $msg);
    }
}
